services:
    # The main container must be specifically named "app"
    app:
        image: ghcr.io/victoralvesf/aonsoku-podcasts:latest
        container_name: aonsoku_podcasts
        env_file:
            - .env.production
        environment:
            - CONTAINER_ROLE=app
            - PHP_OPCACHE_ENABLE=true
        ports:
            - "6060:8080" # You can use any port other than 6060
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        image: mysql:8
        container_name: aonsoku_podcasts_db
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
            interval: 5s
            timeout: 3s
            retries: 5
            start_period: 0s

    queue:
        image: ghcr.io/victoralvesf/aonsoku-podcasts:latest
        container_name: aonsoku_podcasts_queue
        restart: unless-stopped
        env_file:
            - .env.production
        environment:
            - PHP_MEMORY_LIMIT=512M
        stop_signal: SIGTERM
        depends_on:
            - app
        command: [ "sh", "./aonsoku.sh", "queue" ]
        healthcheck:
            test: [ "CMD", "healthcheck-queue" ]
            timeout: 5s
            retries: 3
            start_period: 20s

    scheduler:
        image: ghcr.io/victoralvesf/aonsoku-podcasts:latest
        container_name: aonsoku_podcasts_scheduler
        restart: unless-stopped
        env_file:
            - .env.production
        stop_signal: SIGTERM
        depends_on:
            - app
        command: [ "sh", "./aonsoku.sh", "scheduler" ]
        healthcheck:
            test: [ "CMD", "healthcheck-schedule" ]
            timeout: 5s
            retries: 3
            start_period: 10s

volumes:
    mysql_data:
